=== ardevelop/maindoor-public/feeds/schema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:simpleType name="positiveFloat">
    <xs:restriction base="xs:float">
      <xs:minInclusive value="0.01"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:element name="feed">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="date" type="xs:date"/>
        <xs:element name="offers">
          <xs:complexType>
            <xs:choice>
              <xs:element name="offer" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:choice minOccurs="0" maxOccurs="unbounded">
                    <xs:element name="identifiers">
                      <xs:complexType>
                        <xs:choice minOccurs="0" maxOccurs="unbounded">
                          <xs:element name="local" type="xs:string" minOccurs="0" maxOccurs="1" />
                          <xs:element name="remote" type="xs:string" minOccurs="0" maxOccurs="1"  />
                        </xs:choice>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="type">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:enumeration value="sell" />
                          <xs:enumeration value="rent" />
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element name="price">
                      <xs:complexType>
                        <xs:choice minOccurs="0" maxOccurs="unbounded">
                          <xs:element name="value" type="xs:positiveInteger" minOccurs="0" maxOccurs="1" />
                          <xs:element name="unit" minOccurs="0" maxOccurs="1">
                            <xs:simpleType>
                              <xs:restriction base="xs:string">
                                <xs:enumeration value="usd" />
                                <xs:enumeration value="eur" />
                                <xs:enumeration value="rub" />
                                <xs:enumeration value="gbp" />
                                <xs:enumeration value="chf" />
                              </xs:restriction>
                            </xs:simpleType>
                          </xs:element>
                        </xs:choice>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="property">
                      <xs:complexType>
                        <xs:choice minOccurs="1" maxOccurs="unbounded">
                          <xs:element name="type">
                            <xs:simpleType>
                              <xs:restriction base="xs:string">
                                <xs:enumeration value="apartment" />
                                <xs:enumeration value="apartment:flat" />
                                <xs:enumeration value="apartment:loft" />
                                <xs:enumeration value="apartment:penthouse" />
                                <xs:enumeration value="house" />
                                <xs:enumeration value="house:villa" />
                                <xs:enumeration value="house:manor" />
                                <xs:enumeration value="house:chalet" />
                                <xs:enumeration value="house:cottage" />
                                <xs:enumeration value="house:townhouse" />
                                <xs:enumeration value="castle" />
                                <xs:enumeration value="commercial" />
                                <xs:enumeration value="commercial:hotel" />
                                <xs:enumeration value="commercial:pension" />
                              </xs:restriction>
                            </xs:simpleType>
                          </xs:element>
                          <xs:element name="location">
                            <xs:complexType>
                              <xs:choice minOccurs="0" maxOccurs="unbounded">
                                <xs:element name="latitude">
                                  <xs:simpleType>
                                    <xs:restriction base="xs:double">
                                      <xs:minInclusive value="-90.0"/>
                                      <xs:maxInclusive value="90.0"/>
                                    </xs:restriction>
                                  </xs:simpleType>
                                </xs:element>
                                <xs:element name="longitude">
                                  <xs:simpleType>
                                    <xs:restriction base="xs:double">
                                      <xs:minInclusive value="-180.0"/>
                                      <xs:maxInclusive value="180.0"/>
                                    </xs:restriction>
                                  </xs:simpleType>
                                </xs:element>
                                <xs:element name="address">
                                  <xs:complexType>
                                    <xs:choice minOccurs="0" maxOccurs="unbounded">
                                      <xs:element name="ru" type="xs:string" minOccurs="0" maxOccurs="1" />
                                      <xs:element name="en" type="xs:string" minOccurs="0" maxOccurs="1" />
                                    </xs:choice>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="country" type="xs:string" />
                                <xs:element name="region" type="xs:string" />
                                <xs:element name="location" type="xs:string" />
                              </xs:choice>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="title">
                            <xs:complexType>
                              <xs:choice minOccurs="0" maxOccurs="unbounded">
                                <xs:element name="ru" type="xs:string" />
                                <xs:element name="en" type="xs:string" />
                              </xs:choice>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="article">
                            <xs:complexType>
                              <xs:choice minOccurs="0" maxOccurs="unbounded">
                                <xs:element name="ru" type="xs:string" minOccurs="0" maxOccurs="1" />
                                <xs:element name="en" type="xs:string" minOccurs="0" maxOccurs="1" />
                              </xs:choice>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="images">
                            <xs:complexType>
                              <xs:choice minOccurs="0" maxOccurs="unbounded">
                                <xs:element name="image" minOccurs="0" maxOccurs="unbounded" type="xs:anyURI" />
                              </xs:choice>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="properties">
                            <xs:complexType>
                              <xs:choice minOccurs="0" maxOccurs="unbounded">
                                <xs:element name="area">
                                  <xs:complexType>
                                    <xs:choice minOccurs="0" maxOccurs="unbounded">
                                      <xs:element name="gross" type="positiveFloat" />
                                      <xs:element name="living" type="positiveFloat" />
                                      <xs:element name="kitchen" type="positiveFloat" />
                                      <xs:element name="land" type="positiveFloat" />
                                    </xs:choice>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="rooms">
                                  <xs:complexType>
                                    <xs:choice minOccurs="0" maxOccurs="unbounded">
                                      <xs:element name="total" type="xs:positiveInteger" />
                                      <xs:element name="living" type="xs:positiveInteger" />
                                      <xs:element name="kitchens" type="xs:positiveInteger" />
                                      <xs:element name="bathrooms">
                                        <xs:complexType>
                                          <xs:choice minOccurs="0" maxOccurs="unbounded">
                                            <xs:element name="total" type="xs:positiveInteger" minOccurs="0" maxOccurs="1" />
                                            <xs:element name="toilets" type="xs:positiveInteger" minOccurs="0" maxOccurs="1" />
                                            <xs:element name="bathrooms" type="xs:positiveInteger" minOccurs="0" maxOccurs="1" />
                                            <xs:element name="combined" type="xs:positiveInteger" minOccurs="0" maxOccurs="1" />
                                          </xs:choice>
                                        </xs:complexType>
                                      </xs:element>
                                    </xs:choice>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="building">
                                  <xs:complexType>
                                    <xs:choice minOccurs="0" maxOccurs="unbounded">
                                      <xs:element name="status">
                                        <xs:simpleType>
                                          <xs:restriction base="xs:string">
                                            <xs:enumeration value="project" />
                                            <xs:enumeration value="construction" />
                                            <xs:enumeration value="white_walls" />
                                            <xs:enumeration value="furnished" />
                                            <xs:enumeration value="ready" />
                                            <xs:enumeration value="commissioned" />
                                          </xs:restriction>
                                        </xs:simpleType>
                                      </xs:element>
                                      <xs:element name="material">
                                        <xs:simpleType>
                                          <xs:restriction base="xs:string">
                                            <xs:enumeration value="brick" />
                                            <xs:enumeration value="coquina" />
                                            <xs:enumeration value="wood" />
                                            <xs:enumeration value="beton" />
                                          </xs:restriction>
                                        </xs:simpleType>
                                      </xs:element>
                                      <xs:element name="year">
                                        <xs:simpleType>
                                          <xs:restriction base="xs:integer">
                                            <xs:minInclusive value="1000"/>
                                            <xs:maxInclusive value="2100"/>
                                          </xs:restriction>
                                        </xs:simpleType>
                                      </xs:element>
                                      <xs:element name="floor">
                                        <xs:simpleType>
                                          <xs:restriction base="xs:integer">
                                            <xs:minInclusive value="1"/>
                                            <xs:maxInclusive value="100"/>
                                          </xs:restriction>
                                        </xs:simpleType>
                                      </xs:element>
                                      <xs:element name="floors">
                                        <xs:simpleType>
                                          <xs:restriction base="xs:integer">
                                            <xs:minInclusive value="1"/>
                                            <xs:maxInclusive value="100"/>
                                          </xs:restriction>
                                        </xs:simpleType>
                                      </xs:element>
                                    </xs:choice>
                                  </xs:complexType>
                                </xs:element>
                              </xs:choice>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="tags">
                            <xs:complexType>
                              <xs:choice>
                                <xs:element name="tag" minOccurs="0" maxOccurs="unbounded">
                                  <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                      <xs:enumeration value="yard" />
                                      <xs:enumeration value="garage" />
                                      <xs:enumeration value="sauna" />
                                      <xs:enumeration value="parking" />
                                      <xs:enumeration value="golf" />
                                      <xs:enumeration value="pond" />
                                      <xs:enumeration value="pool" />
                                      <xs:enumeration value="court" />
                                      <xs:enumeration value="furniture" />
                                      <xs:enumeration value="near_sea" />
                                      <xs:enumeration value="near_mountain" />
                                      <xs:enumeration value="smart_home" />
                                      <xs:enumeration value="cabinet" />
                                      <xs:enumeration value="signalling" />
                                      <xs:enumeration value="fireplace" />
                                      <xs:enumeration value="parquet" />
                                      <xs:enumeration value="patio" />
                                      <xs:enumeration value="balcony" />
                                      <xs:enumeration value="gym" />
                                      <xs:enumeration value="autonom_heating" />
                                      <xs:enumeration value="central_heating" />
                                      <xs:enumeration value="downtown" />
                                      <xs:enumeration value="park" />
                                      <xs:enumeration value="view" />
                                      <xs:enumeration value="hunting" />
                                      <xs:enumeration value="fishing" />
                                      <xs:enumeration value="horses" />
                                      <xs:enumeration value="conditioning" />
                                      <xs:enumeration value="climate_control" />
                                      <xs:enumeration value="kitchen_area" />
                                      <xs:enumeration value="office_building" />
                                      <xs:enumeration value="commercial_center" />
                                      <xs:enumeration value="production" />
                                      <xs:enumeration value="cafe" />
                                      <xs:enumeration value="typical_repair" />
                                      <xs:enumeration value="premium_repair" />
                                    </xs:restriction>
                                  </xs:simpleType>
                                </xs:element>
                              </xs:choice>
                            </xs:complexType>
                          </xs:element>
                        </xs:choice>
                      </xs:complexType>
                    </xs:element>
                  </xs:choice>
                </xs:complexType>
              </xs:element>
            </xs:choice>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== ardevelop/maindoor-public/feeds/sample.xml
<?xml version="1.0" encoding="utf-8"?>
<feed xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="schema.xsd">
    <date>2015-01-01</date>
    <offers>
        <offer>
            <identificators>
                <local>1</local>
                <remote>1</remote>
            </identificators>
            <type>sell</type>
            <price>
                <value>100000</value>
                <unit>usd</unit>
            </price>
            <property>
                <type>house:chalet</type>
                <location>
                    <latitude>42.5368920079</latitude>
                    <longitude>1.669921875</longitude>
                    <address>
                        <ru>проспект Беверли-Хиллз</ru>
                        <en>Beverly Hills Avenue</en>
                    </address>
                </location>
                <title>
                    <ru>Шикарный шале в престижной зоне</ru>
                    <en>Luxurious Chalet in the prestigious area</en>
                </title>
                <article>
                    <ru>
                        <h1>Шикарный шале в престижной зоне</h1>
                        <h2>Современный шале класса люкс</h2>
                        <p>Этот шикарный шале расположен в самом лучшем районе города Ла Массана в 5 минутах от
                           спортивно-развлекательного центра Аньёс-Парк (Anyos Park), в 10 минутах от канатной дороги
                           Ла Массаны, ведущей к лыжным трассам Вальнорда и в 5 минутах от единственной в Княжестве
                           частной и престижной международной школы «Col.legi dels Pirineus».</p>
                        <h2>Современный шале класса люкс</h2>
                        <p>Современного стиля комфортабельный шале с отделкой класса люкс находится в привилегированной
                            зоне Ла Массаны, местности –Аньёс. Прекрасные виды на горы. Местонахождение и стиль делают
                            шале уникальным в этом районе.</p>
                    </ru>
                    <en>
                        <h1>Luxurious Chalet in the prestigious area</h1>
                        <h2>Modern luxury chalets</h2>
                        <p>This luxurious Chalet is located in the best area of La Massana 5 minutes from the sports
                           and entertainment centre anyós Park (Anyos Park, 10 minutes from the cable car to La Massana,
                           leading to the ski slopes of Vallnord and 5 minutes from the only in the Principality of
                           private and prestigious international school "Col.legi dels Pirineus".</p>
                        <p>Modern style comfortable Chalet with luxury finishes is located in a privileged area of
                           La Massana, location-agnès. Beautiful mountain views. The location and style make the Chalet
                           is unique in the area.</p>
                    </en>
                </article>
                <images>
                    <image>http://static.maindoor.ru/dcf91d545ec811e48e28005056006cc7.JPG</image>
                    <image>http://static.maindoor.ru/f4bbac385ed011e48e28005056006cc7.JPG</image>
                    <image>http://static.maindoor.ru/f4c0f6de5ed011e48e28005056006cc7.JPG</image>
                    <image>http://static.maindoor.ru/f4bbac385ed011e48e28005056006cc7.JPG</image>
                    <image>http://static.maindoor.ru/f4cf70385ed011e48e28005056006cc7.JPG</image>
                    <image>http://static.maindoor.ru/f4d438205ed011e48e28005056006cc7.JPG</image>
                    <image>http://static.maindoor.ru/f4d6fbbe5ed011e48e28005056006cc7.JPG</image>
                    <image>http://static.maindoor.ru/f4eca5d65ed011e48e28005056006cc7.JPG</image>
                    <image>http://static.maindoor.ru/f4fe09025ed011e48e28005056006cc7.JPG</image>
                    <image>http://static.maindoor.ru/f52d6b485ed011e48e28005056006cc7.jpg</image>
                </images>
                <properties>
                    <area>
                        <gross>560</gross>
                        <living>483</living>
                        <kitchen>90</kitchen>
                        <land>100</land>
                    </area>
                    <rooms>
                        <total>7</total>
                        <living>5</living>
                        <kitchens>1</kitchens>
                        <bathrooms>
                            <total>5</total>
                            <toilets>2</toilets>
                            <bathrooms>2</bathrooms>
                            <combined>1</combined>
                        </bathrooms>
                    </rooms>
                    <building>
                        <status>commissioned</status>
                        <material>brick</material>
                        <year>2007</year>
                        <floor>4</floor>
                        <floors>4</floors>
                    </building>
                </properties>
                <tags>
                    <tag>near_mountain</tag>
                    <tag>furniture</tag>
                    <tag>garage</tag>
                </tags>
            </property>
        </offer>
    </offers>
</feed>

=== ardevelop/maindoor-public/feeds/sample_luxdom.xml
<?xml version="1.0" encoding="utf-8"?>
<feed xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://github.com/difiz/maindoor-public/blob/master/feeds/schema.xsd">
<date>2014-01-01</date>
<offers>
    <offer>
        <property>
            <title>
                <ru>Квартира</ru>
                <en>Flat</en>
            </title>
            <tags>
                <tag>balcony</tag>
            </tags>
            <location>
                <latitude>55.7617020906</latitude>
                <longitude>37.6062011719</longitude>
            </location>
            <images>
                <image>http://www.luxdom.ru/images/objects/object_buy_759/1221%20(1).jpg</image>
                <image>http://www.luxdom.ru/images/objects/object_buy_759/1221%20(3).jpg</image>
                <image>http://www.luxdom.ru/images/objects/object_buy_759/1221%20(4).jpg</image>
                <image>http://www.luxdom.ru/images/objects/object_buy_759/1221%20(5).jpg</image>
                <image>http://www.luxdom.ru/images/objects/object_buy_759/1221%20(2).jpg</image>
                <image>http://www.luxdom.ru/images/objects/object_buy_759/1221.jpg</image>
                <image>http://www.luxdom.ru/images/objects/object_buy_759/DSC06777_s.jpg</image>
                <image>http://www.luxdom.ru/images/objects/object_buy_759/DSC06778_s.jpg</image>
                <image>http://www.luxdom.ru/images/objects/object_buy_759/DSC06779_s.jpg</image>
            </images>
            <article>
                <ru>Доходный дом купца Филатова, парадный подъезд, сделан ремонт, 3 спальни, кухня-гостиная, 2 санузла, 2-сторонняя квартира, вид на Храм Христа Спасителя, МИД, Кремль, свободна. В подъездах установлены домофоны, работает консьерж. Инфраструктура обжитого района, в шаговой доступности находится храм Христа Спасителя. </ru>
            </article>
            <type>apartment:flat</type>
            <properties>
                <building>
                    <floors>5</floors>
                    <floor>4</floor>
                </building>
                <rooms>
                    <living>4</living>
                    <bathrooms>
                        <total>2</total>
                        <combined>2</combined>
                    </bathrooms>
                </rooms>
                <area>
                    <gross>154.0</gross>
                    <kitchen>18.0</kitchen>
                    <living>86.2</living>
                </area>
            </properties>
        </property>
        <price>
            <unit>usd</unit>
            <value>2200000</value>
        </price>
        <identifiers>
            <remote>1151</remote>
        </identifiers>
        <type>sell</type>
    </offer>
</offers>
</feed>
